language: node_js
node_js:
- '4.1'
- '4.0'
- '0.12'
- '0.11'
sudo: false
env:
  matrix:
  - GROUP=
  global:
  - GHREPO=github.com/jupyter/jupyter-js-output-area.git
  - secure: ilV0GdOJ5N6xPwRYJuXxHVaK133PJeRHf5lOqYD+o7/8uQ7+YQEnq/GB345yZ4yaxYITbYq+CAB9YxkfvDig5qUKWmnSFVFjl+1hcaWwuRqX7jt3G35EptgkpgnAHxcuLyYUNhiESTsF/33bbeaedoAmTDK6b6aopUsw96d5C+p2Kkv4RXUQy48SBXQ3abGkUnpu6VsNXDEjaFNoHu8QUY0kYgrd9Mv2SeVYRljqu1/f1/eeANqt3CJO6lmYalZCjhmPsvGSbPY7gUXCIhw8JzIA6CFNHKKqjHcP2jk8cCEQYG07d0LhXKPsZ3BJTSM+IW70El5KaxE/X10f7CuTtVp+BOa2iURyOZcni04/wlwPWIONjh3KObaaf2RJvBTnIjLbSYJhFx3Uyul8yNF5jlA5tIrALOyRhhLYlkQiqy5jrmLsATOAZSCM8a2uMgfVQ3KxSTzs1iuA405uLMIHP1QwcXO4vYNFVyg0lV1L1l8N712ikiC6NqgdIsXSazwPhd3ZKGnV25Y/cRsmVSfoNH9RiSGUjH9cGyIljrbpCJZ5Jvx+pKXHOU6JNjJRBJh5AZ0IFTpPSh0z2EHpPoFXEdulwPYEpdXbtLdoRyvZ2FiNOViQG+I+mRnhrGUCoy5WmponC1lVm10XR8fQPJvsln+6YeuIos/0mX7BJxBZrko=
install:
- bash scripts/travis_install.sh
script:
- bash scripts/travis_script.sh
after_success:
- bash scripts/travis_after_success.sh
